class Paths(object):
    # Should not be used elsewhere
    APPRECIATE = "/appreciate"
    PROMOTE = "/promote"
    SEND = "/send"
    ENABLE = "/enable"
    DISABLE = "/disable"
    FLAG = "/flag"
    BENEFICIARY = "/beneficiary"
    AUTHOR = "/author"
    EMAIL = "/email"
    OUTSTANDING = "/outstanding"
    ACCEPT = "/accept"
    DENY = "/deny"
    SEND = "/send"
    FLAG = "/flag"
    CHANGE = "/change"
    PENDING_ACTIONS = "/pending"
    RESET = "/reset"
    REMOVE = "/remove"
    DELETE = "/delete"
    PAYMENT = "/payment"
    PURCHASE = "/purchase"
    RESPONSE = "/response"
    SHOW = "/show"
    HIDE = "/hide"

    # General
    INDEX = "/"
    INVALID = "/invalid"
    FAILURE = "/failure"
    
    # Statistics
    STATS = "/stats"
    STATS_TOTALS = STATS + "/totals"
    
    # Authentication
    LOGOUT = "/logout"
    LOGOUT_SUCCESS = "/logout/success"
    LOGOUT_FAILURE = "/logout/failure"
    LOGIN = "/login"
    LOGIN_SUCCESS = "/login/success"
    LOCKED = "/locked"
    DENIED = "/denied"
    EXPIRED = "/expired"
    REGISTER = "/register"
    
    # Users
    USERS = "/users"
    USERS_ID = USERS + "/{0}"
    USERS_CURRENT = "/current"
    PROFILE = "/profile"
    ROLES = "/roles"
    APPRECIATION_RESPONSE = RESPONSE
    USERS_APPRECIATION_RESPONSE = USERS_ID + RESPONSE
    USERS_ROLES = ROLES
    USERS_ACCEPT = USERS_CURRENT + ACCEPT
    CONFIRMATION = "/confirmation"
    CONFIRMATION_SEND = CONFIRMATION + SEND
    PAYMENT_CHANGE_REQUEST = PAYMENT + SEND
    PAYMENT_CHANGE = PAYMENT + CHANGE
    EMAIL_PENDING_ACTION_CHANGE = EMAIL + PENDING_ACTIONS
    EMAIL_CHANGE = EMAIL + CHANGE
    EMAIL_CHANGE_REQUEST = EMAIL
    PASSWORD_CHANGE = "/password"
    PASSWORD_UNAUTHED_CHANGE = PASSWORD_CHANGE + USERS + "/{0}"
    PASSWORD_RESET = PASSWORD_CHANGE + RESET
    USERS_DELETE = USERS_CURRENT + DELETE
    USERS_DELETE_SEND = USERS_CURRENT + DELETE + SEND
    LOCATIONS = "/locations"
    LOCATIONS_REMOVE = LOCATIONS + REMOVE
    
    # Finances
    FINANCES = "/finances"
    
    # Payment
    CURRENCY_PURCHASE = "/currency" + PURCHASE
    PAYMENT_CHECK = PAYMENT
    
    # Notifications
    NOTIFICATIONS = "/notifications"

    # Messages
    MESSAGES = "/messages"
    MESSAGES_CONVERSATION = MESSAGES + USERS + "/{0}"
    MESSAGES_CONVERSATION_MESSAGES = MESSAGES + USERS + "/{0}" + MESSAGES
    MESSAGES_CONVERSATION_FLAG = MESSAGES_CONVERSATION + FLAG
    MESSAGES_CONVERSATION_SHOW = MESSAGES_CONVERSATION + SHOW
    
    # Postings
    POSTINGS = "/postings"
    POSTINGS_ID = POSTINGS + "/{0}"
    POSTINGS_APPRECIATE = POSTINGS_ID + APPRECIATE
    POSTINGS_PROMOTE = POSTINGS_ID + PROMOTE
    POSTINGS_AUTHOR = USERS_ID + POSTINGS + AUTHOR
    POSTINGS_BENEFICIARY = USERS_ID + POSTINGS + BENEFICIARY
    POSTINGS_ID_ENABLE = POSTINGS_ID + ENABLE
    POSTINGS_ID_DISABLE = POSTINGS_ID + DISABLE
    POSTINGS_ID_FLAG = POSTINGS_ID + FLAG
    POSTINGS_ID_EDIT = POSTINGS_ID + CHANGE
    
    # Tags
    TAGS = "/tags"
    TAGS_ID = TAGS + "/{0}"
    
    # Comments
    COMMENTS = "/comments"
    COMMENTS_ID = COMMENTS + "/{0}"
    COMMENTS_APPRECIATE = COMMENTS_ID + APPRECIATE
    COMMENTS_PROMOTE = COMMENTS_ID + PROMOTE
    POSTINGS_COMMENTS = POSTINGS_ID + COMMENTS
    USERS_COMMENTS = USERS_ID + COMMENTS
    TAGS_COMMENTS = TAGS_ID + COMMENTS
    COMMENTS_COMMENTS = COMMENTS_ID + COMMENTS
    COMMENTS_AUTHOR = USERS_ID + COMMENTS + AUTHOR
    COMMENTS_BENEFICIARY = USERS_ID + COMMENTS + BENEFICIARY
    COMMENTS_ID_ENABLE = COMMENTS_ID + ENABLE
    COMMENTS_ID_DISABLE = COMMENTS_ID + DISABLE
    COMMENTS_ID_FLAG = COMMENTS_ID + FLAG
    COMMENTS_ID_EDIT = COMMENTS_ID + CHANGE
    
    # Backing
    BACKINGS = "/backings"
    BACKINGS_OUTSTANDING = BACKINGS + "/outstanding"
    BACKINGS_ID = BACKINGS + USERS + "/{0}"
    BACKINGS_OUTSTANDING_ID = BACKINGS_OUTSTANDING + USERS + "/{0}"
    
    # Offers
    OFFERS = "/offers"
    OFFERS_OUTSTANDING = OFFERS + "/outstanding"
    OFFERS_ID = OFFERS + USERS + "/{0}"
    OFFERS_OUTSTANDING_ID = OFFERS_OUTSTANDING + USERS + "/{0}"
    OFFERS_ACCEPT = OFFERS_ID + "/accept"
    OFFERS_DENY = OFFERS_ID + "/deny"
    OFFERS_WITHDRAW = OFFERS_OUTSTANDING_ID + "/withdraw"
    
    # Offers Email
    OFFERS_EMAIL = OFFERS + "/email"
    OFFERS_EMAIL_ID = OFFERS_EMAIL + "/{0}" + OFFERS
    OFFERS_OUTSTANDING_EMAIL = OFFERS_OUTSTANDING + EMAIL
    OFFERS_OUTSTANDING_EMAIL_ID = OFFERS_OUTSTANDING_EMAIL + "/{0}" + OFFERS
    OFFERS_EMAIL_ACCEPT = OFFERS_ID + EMAIL + ACCEPT
    OFFERS_EMAIL_DENY = OFFERS_ID + EMAIL + DENY
    OFFERS_EMAIL_WITHDRAW = OFFERS_OUTSTANDING_EMAIL_ID + "/withdraw"

    # Subscription
    SUBSCRIPTION = "/subscription"
    FOLLOWEES = "/followees"
    FOLLOWEES_ID = FOLLOWEES + USERS + "/{0}"
    USER_FOLLOWEES = USERS_ID + FOLLOWEES
    FOLLOWERS = "/followers"
    FOLLOWERS_ID = FOLLOWERS + USERS + "/{0}"
    USER_FOLLOWERS = USERS_ID + FOLLOWERS
    
    FEED = "/feed"
    
    BLOCKED = "/blocked"
    BLOCKED_ID = BLOCKED + USERS + "/{0}"
    
    # Settings
    SETTINGS = "/settings"
    
    FEEDBACKS = "/feedbacks"
    
class AdminPaths(object):
    # Should not be used elsewhere
    APPRECIATE = "/appreciate"
    ADD = "/add"
    REMOVE = "/remove"
    CHANGE = "/change"
    LOCK = "/lock"
    UNLOCK = "/unlock"
    FLAG = "/flag"
    WARNING = "/warning"
    TARGET = "/target"
    TALLY_CHANGE = "/tally" + CHANGE
    RESTRICTED = "/restricted"
    RENAME = "/rename"
    ACTIONS = "/actions"
    CACHE = "/cache"
    
    ADMIN = "/admin"
    ADMIN_USER = ADMIN + Paths.USERS + "/{0}"
    ADMIN_TARGET = ADMIN + TARGET + "/{0}"
    ADMIN_POSTING = ADMIN + Paths.POSTINGS + "/{0}"
    ADMIN_COMMENT = ADMIN + Paths.COMMENTS + "/{0}"
    ADMIN_TAG = ADMIN + Paths.TAGS + "/{0}"
    
    # Admin Check
    ADMIN_CHECK = ADMIN
    
    # Authentication
    ADMIN_LOGOUT_USER = ADMIN_TARGET + Paths.LOGOUT
    
    # Statistics
    ADMIN_STATISTICS_CACHE = ADMIN + Paths.STATS + CACHE
    
    # Users
    ADMIN_EMAIL_CHANGE = ADMIN_TARGET + Paths.EMAIL_CHANGE
    ADMIN_EMAIL_CHANGE_REQUEST = ADMIN_TARGET + Paths.EMAIL_CHANGE_REQUEST
    ADMIN_CONFIRMATION = ADMIN_TARGET + Paths.CONFIRMATION
    ADMIN_PASSWORD_RESET = ADMIN_TARGET + Paths.PASSWORD_RESET
    ADMIN_USERS_CURRENT = ADMIN_TARGET + Paths.USERS_CURRENT
    ADMIN_USERS_UNLOCK = ADMIN_USER + UNLOCK
    ADMIN_USERS_LOCK = ADMIN_USER + LOCK
    ADMIN_USERS_DELETE = ADMIN_TARGET + Paths.USERS_DELETE
    ADMIN_USERS_PROFILE = ADMIN_TARGET + Paths.PROFILE
    ADMIN_USERS_APPRECIATION_RESPONSE = ADMIN_TARGET + Paths.APPRECIATION_RESPONSE
    ADMIN_USERS_ROLES = ADMIN_USER + Paths.ROLES
    ADMIN_USERS_PENDING_ACTIONS = ADMIN_TARGET + Paths.PENDING_ACTIONS
    ADMIN_ROLES = ADMIN_TARGET + Paths.ROLES
    ADMIN_USERS_LOGIN_ATTEMPTS = ADMIN_USER + "/loginAttempts"
    ADMIN_USERS_RENAME = ADMIN_USER + RENAME
    ADMIN_USERS_PASSWORD = ADMIN_USER + "/password"
    
    # Finance
    ADMIN_FINANCES = ADMIN_TARGET + Paths.FINANCES
    ADMIN_FINANCES_ADD = ADMIN_USER + Paths.FINANCES + ADD
    ADMIN_FINANCES_REMOVE = ADMIN_USER + Paths.FINANCES + REMOVE
    
    # Notifications
    ADMIN_NOTIFICATIONS = ADMIN_TARGET + Paths.NOTIFICATIONS
    
    # Feed
    ADMIN_FEED = ADMIN_TARGET + Paths.FEED
    
    # Postings
    ADMIN_POSTINGS_ID = ADMIN_POSTING
    ADMIN_POSTINGS_ID_REMOVE = ADMIN_POSTING + REMOVE
    ADMIN_POSTINGS_ID_FLAG = ADMIN_POSTING + FLAG
    ADMIN_POSTINGS_ID_WARNING = ADMIN_POSTING + WARNING
    ADMIN_POSTINGS_ID_ENABLE = ADMIN_TARGET + Paths.POSTINGS_ID_ENABLE
    ADMIN_POSTINGS_ID_DISABLE = ADMIN_TARGET + Paths.POSTINGS_ID_DISABLE
    ADMIN_POSTINGS_ID_TALLY_CHANGE = ADMIN_POSTING + TALLY_CHANGE
    ADMIN_POSTINGS_ID_APPRECIATE = ADMIN_POSTING + TARGET + "/{0}" + APPRECIATE
    
    # Comments
    ADMIN_COMMENTS_ID = ADMIN_COMMENT
    ADMIN_COMMENTS_ID_REMOVE = ADMIN_COMMENT + REMOVE
    ADMIN_COMMENTS_ID_FLAG = ADMIN_COMMENT + FLAG
    ADMIN_COMMENTS_ID_WARNING = ADMIN_COMMENT + WARNING
    ADMIN_COMMENTS_ID_ENABLE = ADMIN_TARGET + Paths.COMMENTS_ID_ENABLE
    ADMIN_COMMENTS_ID_DISABLE = ADMIN_TARGET + Paths.COMMENTS_ID_DISABLE
    ADMIN_COMMENTS_ID_TALLY_CHANGE = ADMIN_COMMENT + TALLY_CHANGE
    ADMIN_COMMENTS_ID_APPRECIATE = ADMIN_COMMENT + TARGET + "/{0}" + APPRECIATE
    
    # Tags
    ADMIN_TAGS_ID_LOCK = ADMIN_TAG + LOCK
    ADMIN_TAGS_ID_UNLOCK = ADMIN_TAG + UNLOCK
    
    # Following
    ADMIN_SUBSCRIPTION = ADMIN_TARGET + Paths.SUBSCRIPTION
    ADMIN_FOLLOWEES = ADMIN_TARGET + Paths.FOLLOWEES
    ADMIN_FOLLOWERS = ADMIN_TARGET + Paths.FOLLOWERS
    ADMIN_FOLLOWEES_ID = ADMIN_TARGET + Paths.FOLLOWEES_ID
    ADMIN_FOLLOWERS_ID = ADMIN_TARGET + Paths.FOLLOWERS_ID
    
    # Blocking
    ADMIN_BLOCKED = ADMIN_TARGET + Paths.BLOCKED
    ADMIN_BLOCKED_ID = ADMIN_TARGET + Paths.BLOCKED_ID
    
    # Backing
    ADMIN_BACKINGS = ADMIN_TARGET + Paths.BACKINGS
    ADMIN_BACKINGS_ID =  ADMIN_TARGET + Paths.BACKINGS_ID
    ADMIN_BACKINGS_OUTSTANDING = ADMIN_TARGET + Paths.BACKINGS_OUTSTANDING
    ADMIN_BACKINGS_OUTSTANDING_ID = ADMIN_TARGET + Paths.BACKINGS_OUTSTANDING_ID
    
    # Offer
    ADMIN_OFFERS = ADMIN_TARGET + Paths.OFFERS
    ADMIN_OFFERS_ID = ADMIN_TARGET + Paths.OFFERS_ID
    ADMIN_OFFERS_OUTSTANDING = ADMIN_TARGET + Paths.OFFERS_OUTSTANDING
    ADMIN_OFFERS_OUTSTANDING_ID = ADMIN_TARGET + Paths.OFFERS_OUTSTANDING_ID
    ADMIN_OFFERS_OUTSTANDING_EMAIL = ADMIN_TARGET + Paths.OFFERS_OUTSTANDING_EMAIL
    ADMIN_OFFERS_OUTSTANDING_EMAIL_ID = ADMIN_TARGET + Paths.OFFERS_OUTSTANDING_EMAIL_ID
    ADMIN_OFFERS_EMAIL_WITHDRAW = ADMIN_TARGET + Paths.OFFERS_EMAIL_WITHDRAW
    ADMIN_OFFERS_WITHDRAW = ADMIN_TARGET + Paths.OFFERS_WITHDRAW
    
    # Settings
    ADMIN_SETTINGS = ADMIN_TARGET + Paths.SETTINGS
    
    # Feedback
    ADMIN_FEEDBACKS = ADMIN + Paths.FEEDBACKS
    ADMIN_FEEDBACKS_CHANGE = ADMIN_FEEDBACKS + CHANGE
    ADMIN_FEEDBACKS_ID = ADMIN_FEEDBACKS + "/{0}"
    
    # Restricted
    ADMIN_RESTRICTEDS = ADMIN + RESTRICTED
    ADMIN_RESTRICTEDS_ID = ADMIN_RESTRICTEDS + "/{0}";
    
    # Admin Actions
    ADMIN_ACTIONS = ADMIN + ACTIONS
    
class Codes(object):
    SUCCESS = 200
    CREATED = 201
    DELETED = 204
    
    FAILURE = 400
    DENIED = 401
    INVALID = 420
    NOT_ALLOWED = 424
    LIMIT = 425
    LOCKED = 403
    LOGIN_LOCKED = 430
    EXPIRED = 419
    EXISTS = 409
    EXISTS_USERNAME = 481
    EXISTS_EMAIL = 482
    NOT_FOUND = 410
    BALANCE = 412
    PAGEABLE = 416
    PARAMETER = 449

    EXTERNAL_SERVICE = 520
    FEATURE_DISABLED = 521
    
    ERROR = 500
    FINANCE = 500
    
    RESTRICTED = 460
    RESTRICTED_USERNAME = 461
    RESTRICTED_PASSWORD = 462
    RESTRICTED_EMAIL = 463
    THROTTLED_ADDRESS = 429

#comment out the correct one
class HasCacheTimes(object):
    A = 0
    #class CacheTimes(object):
    USER_USERNAME = 0
    USER_INFO = 0
    FINANCE = 0

    POSTING = 0
    COMMENT = 0
    TAG = 0
    SUBSCRIPTION = 0

    PAGED = 0

class CacheTimes(object):
    USER_USERNAME = 10
    USER_INFO = 15
    FINANCE = 15

    POSTING = 30
    COMMENT = 30
    TAG = 120
    SUBSCRIPTION = 30

    PAGED = 120
